### ISSUE TITLE
Support to change path of js

### ISSUE THREAD

**Issue by newbe36524** [excubo-ag/Blazor.ScriptInjection#26]
I am developing a Chrome extension with Blazor, and `_content` folder is forbidden to load in browser extension since it is build in restriction.
So, I need to load js from some folder like `content` instead of `_content`.

You can check out my source code to see what I am doing at https://github.com/Amazing-Favorites/Amazing-Favorites if you are interested in

**Comment by stefanloerwald** [comment]
Hi @newbe36524,

I don't think there's anything this library can do about the paths. That's just the way the Blazor framework does it.

In can't quite understand why you need this library in the first place. Surely you can simply download all js files on extension installation, without need for lazy loading. Also, Blazor comes with the import feature for js modules since dotNet5, so that's strictly preferable, in my opinion.

Hope that helps,
Stefan

**Comment by newbe36524** [comment]
> Hi @newbe36524,
> 
> I don't think there's anything this library can do about the paths. That's just the way the Blazor framework does it.
> 
> In can't quite understand why you need this library in the first place. Surely you can simply download all js files on extension installation, without need for lazy loading. Also, Blazor comes with the import feature for js modules since dotNet5, so that's strictly preferable, in my opinion.
> 
> Hope that helps,
> Stefan

Hi,

Actually, what I really concern about is the path is hard code at https://github.com/excubo-ag/Blazor.ScriptInjection/blob/main/ScriptInjection/AddScript.cs#L34

I need to change the path to `content/Excubo.Blazor.ScriptInjection/` since `_content` is a reserved folder in Chrome extension, actually, all folders with `_` prefix are reserved folders.

Why do I need this component?

I add a feature that my application with collect user anonymous data if the user turns it on in UserOptions. So there is some code like
```cs
@if (_userOptions is
{
    AcceptPrivacyAgreement: true,
    ApplicationInsightFeature:
    {
        Enabled: true
        }
    })
{
    <AddScript Src="content/ai.js" Async="false" Defer="false"/>
}
```

I just think it looks better to use the full Blazor format as above

For now, I just copy `AddScript` and change the path in my code to fix my case.
If you don't think this scenario needs to be adapted in your library, I think it is ok to close this issue.

**Comment by stefanloerwald** [comment]
I would still recommend to use the native blazor mechanism for dynamic imports, i.e. https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#javascript-isolation-in-javascript-modules-1

It is superior to this library, which was developed prior to the native blazor feature. Since you target net6, there's no point in using this rather old library.

**Comment by newbe36524** [comment]
It makes sense, thank you.
